user www-data; 
worker_processes auto;
pid /run/nginx.pid;
events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types; #Важно для images, js, cdd и т.д - Для корректной обработки бразуером контента
  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log;
  include /etc/nginx/sites-enabled/*;
  upstream app{
  server 172.19.156.30:7432;
  server 172.19.156.30:8081 weight=3;
  server 172.19.156.30:8082 weight=2;
  }
  upstream gitlab{ 
  server 192.168.92.134:80;  
  }
}